FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["./data/blazor_bootcamp/blazor_bootcamp.csproj", "."]
RUN dotnet restore "blazor_bootcamp.csproj"
COPY . .
RUN dotnet build "./data/blazor_bootcamp/blazor_bootcamp.csproj" -c Release -o /app/build
RUN dotnet publish "./data/blazor_bootcamp/blazor_bootcamp.csproj" -c Release -o /app/publish
WORKDIR /app
ENTRYPOINT ["dotnet", "blazor_bootcamp.dll"]