FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app/src
COPY ["./data/blazor_bootcamp", "."]
RUN dotnet restore "TangyWeb_Server/TangyWeb_Server.csproj" && \
    dotnet restore "TangyWeb_Client/TangyWeb_Client.csproj" && \
    dotnet restore "Tangy_Models/Tangy_Models.csproj"

RUN dotnet build "TangyWeb_Server/TangyWeb_Server.csproj" -c Development -o "/app/bin" && \
    dotnet build "TangyWeb_Client/TangyWeb_Client.csproj" -c Development -o "/app/bin" && \
    dotnet build "Tangy_Models/Tangy_Models.csproj" -c Development -o "/app/bin"

FROM build AS final
EXPOSE 5000
#EXPOSE 443
WORKDIR /app
RUN dotnet dev-certs https --clean && dotnet dev-certs https --trust
ENTRYPOINT ["dotnet", "watch", "run", "--project", "/app/src/TangyWeb_Server/TangyWeb_Server.csproj", "--urls", "http://0.0.0.0:5000"]